added -c option to create new profile

diff --git a/npmrc b/npmrc
--- a/npmrc
+++ b/npmrc
@@ -3,12 +3,29 @@
 NPMRC_STORE="${HOME}/.npmrcs";
 NPMRC="${HOME}/.npmrc";
 
+printUsage() {
+  echo ""
+  echo "Usage: npmrc [-c] [name]"
+}
+
+activate() {
+  if [ ! -e "${NPMRC_STORE}/${1}" ]; then
+    echo "Couldn't find npmrc file '${1}', looked in ${NPMRC_STORE}/${1}";
+    exit 1;
+  fi;
+
+  echo "Removing old .npmrc ($(readlink ${NPMRC}))";
+  rm -f "${NPMRC}" || exit 1;
+
+  echo "Activating .npmrc '${1}'";
+  ln -s "${NPMRC_STORE}/${1}" "${NPMRC}" || exit 1;
+}
+
 if [ "${1}" = "--help" -o "${1}" = "-h" ]; then
   echo "npmrc"
   echo ""
   echo "  Switch between different .npmrc files with ease and grace."
-  echo ""
-  echo "Usage: npmrc [name]"
+  printUsage;
   echo ""
   echo "Example:"
   echo "  Creating and activating a new .npmrc called 'work':"
@@ -51,11 +68,6 @@ if [ "x${1}" = "x" ]; then
   exit 0;
 fi;
 
-if [ ! -e "${NPMRC_STORE}/${1}" ]; then
-  echo "Couldn't find npmrc file '${1}', looked in ${NPMRC_STORE}/${1}";
-  exit 1;
-fi;
-
 if [ -e "${NPMRC}" ]; then
   if [ ! -h "${NPMRC}" ]; then
     echo "Current .npmrc (${NPMRC}) is not a symlink. You may want to copy it into ${NPMRC_STORE}";
@@ -66,10 +78,24 @@ if [ -e "${NPMRC}" ]; then
     echo "Current .npmrc (${NPMRC}) is already '${1}' (${NPMRC_STORE}/${1})";
     exit 1;
   fi;
-
-  echo "Removing old .npmrc ($(readlink ${NPMRC}))";
-  rm "${NPMRC}" || exit 1;
 fi;
 
-echo "Activating .npmrc '${1}'";
-ln -s "${NPMRC_STORE}/${1}" "${NPMRC}" || exit 1;
+if [ "${1}" = "--create" -o "${1}" = "-c" ]; then
+  if [ "x${2}" = "x" ]; then
+    echo "What do you want to call your new npm configuration?"
+    printUsage;
+    exit 1;
+  fi
+
+  if [ -e "${NPMRC_STORE}/${2}" ]; then
+    echo "npmrc file '${2}', already exists: ${NPMRC_STORE}/${2}";
+    exit 1;
+  fi;
+
+  touch ${NPMRC_STORE}/${2}
+
+  activate $2
+  exit 0;
+fi
+
+activate $1
